export type BilingualLabel = { en: string; zh: string };

export const moduleLabels = {
  dashboard: { en: 'Dashboard', zh: '仪表盘' }, overview: { en: 'Overview', zh: '总览' }, stocks: { en: 'Stocks', zh: '股票' }, etfs: { en: 'ETFs', zh: 'ETF' }, research: { en: 'Research', zh: '研究' }, markets: { en: 'Markets', zh: '市场' }, macroNav: { en: 'Macro', zh: '宏观' }, calendar: { en: 'Calendar', zh: '日历' }, newsNav: { en: 'News', zh: '新闻' }, dcaSimulation: { en: 'DCA Simulation', zh: '定投模拟' }, settings: { en: 'Settings', zh: '设置' },
  marketOverview: { en: 'Global Market Overview', zh: '全球市场总览' }, treasuryYields: { en: 'Treasury Yields', zh: '美国国债收益率' }, crypto: { en: 'Crypto', zh: '加密资产' }, macroIndicators: { en: 'Macro Indicators', zh: '宏观经济指标' }, economicCalendar: { en: 'Economic Calendar', zh: '经济日历' }, marketNews: { en: 'Latest News', zh: '最新市场新闻' }, keyPeople: { en: 'Key People', zh: '关键人物' }, moreMarkets: { en: 'More Markets', zh: '更多市场' }, moreMacro: { en: 'Additional US Macro', zh: '更多美国宏观经济指标' }, watchlist: { en: 'Watchlist', zh: '自选关注' },
} satisfies Record<string, BilingualLabel>;

export const assetLabels: Record<string, BilingualLabel> = {
  QQQM: { en: 'Invesco NASDAQ 100 ETF', zh: '纳斯达克100 ETF' }, SPYM: { en: 'SPDR Portfolio S&P 500 ETF', zh: '标普500 ETF' }, DIA: { en: 'SPDR Dow Jones Industrial Average ETF', zh: '道琼斯工业平均 ETF' }, SMH: { en: 'VanEck Semiconductor ETF', zh: '半导体 ETF' }, VGT: { en: 'Vanguard Information Technology ETF', zh: '信息技术 ETF' }, SOXX: { en: 'iShares Semiconductor ETF', zh: '半导体 ETF' }, SCHD: { en: 'Schwab U.S. Dividend Equity ETF', zh: '美国股息股票 ETF' }, RSP: { en: 'Invesco S&P 500 Equal Weight ETF', zh: '标普500等权重 ETF' }, SPMO: { en: 'Invesco S&P 500 Momentum ETF', zh: '标普500动量 ETF' }, AVUV: { en: 'Avantis U.S. Small Cap Value ETF', zh: '美国小盘价值 ETF' }, XLK: { en: 'Technology Select Sector SPDR Fund', zh: '美国科技行业 ETF' }, XLV: { en: 'Health Care Select Sector SPDR Fund', zh: '美国医疗保健 ETF' }, VT: { en: 'Vanguard Total World Stock ETF', zh: '全球股票 ETF' }, HACK: { en: 'ETFMG Prime Cyber Security ETF', zh: '网络安全 ETF' }, VXUS: { en: 'Vanguard Total International Stock ETF', zh: '美国以外全球股票 ETF' }, VYMI: { en: 'Vanguard International High Dividend Yield ETF', zh: '国际高股息 ETF' }, IGV: { en: 'iShares Expanded Tech-Software Sector ETF', zh: '软件行业 ETF' }, FMTM: { en: 'MarketDesk Focused U.S. Momentum ETF', zh: '美国聚焦动量 ETF' },
  NVDA: { en: 'NVIDIA', zh: '英伟达' }, MU: { en: 'Micron Technology', zh: '美光科技' }, TSLA: { en: 'Tesla', zh: '特斯拉' }, AAPL: { en: 'Apple', zh: '苹果' }, AVGO: { en: 'Broadcom', zh: '博通' }, MSFT: { en: 'Microsoft', zh: '微软' }, META: { en: 'Meta Platforms', zh: 'Meta' }, AMZN: { en: 'Amazon', zh: '亚马逊' }, GOOGL: { en: 'Alphabet (Google)', zh: '谷歌' }, COST: { en: 'Costco', zh: '好市多' }, WMT: { en: 'Walmart', zh: '沃尔玛' }, PDD: { en: 'PDD Holdings', zh: '拼多多' }, NFLX: { en: 'Netflix', zh: '奈飞' }, RDDT: { en: 'Reddit', zh: 'Reddit' }, 'BRK.B': { en: 'Berkshire Hathaway', zh: '伯克希尔·哈撒韦' }, AMD: { en: 'Advanced Micro Devices', zh: 'AMD' }, INTC: { en: 'Intel', zh: '英特尔' }, TSM: { en: 'Taiwan Semiconductor', zh: '台积电' }, MRVL: { en: 'Marvell Technology', zh: '迈威尔科技' },
  '^DJI': { en: 'Dow Jones Industrial Average (DJIA)', zh: '道琼斯工业平均指数' }, '^GSPC': { en: 'S&P 500', zh: '标普500指数' }, '^IXIC': { en: 'Nasdaq Composite', zh: '纳斯达克综合指数' }, '^N225': { en: 'Nikkei 225', zh: '日经225指数' }, '^STOXX': { en: 'STOXX Europe 600', zh: '欧洲STOXX 600指数' }, 'GC=F': { en: 'Gold', zh: '黄金' }, 'CL=F': { en: 'WTI Crude Oil', zh: 'WTI原油' },
  CSI300: { en: 'CSI 300', zh: '沪深300指数' }, SPX: { en: 'S&P 500', zh: '标普500指数' }, IXIC: { en: 'Nasdaq Composite', zh: '纳斯达克综合指数' }, HSI: { en: 'Hang Seng Index', zh: '恒生指数' }, VIX: { en: 'VIX', zh: '恐慌指数' },
  US2Y: { en: 'US 2-Year Treasury Yield', zh: '美国2年期国债收益率' }, US10Y: { en: 'US 10Y Treasury Yield', zh: '美国10年期国债收益率' }, US30Y: { en: 'US 30-Year Treasury Yield', zh: '美国30年期国债收益率' }, BTC: { en: 'Bitcoin', zh: '比特币' }, bitcoin: { en: 'Bitcoin', zh: '比特币' }, ethereum: { en: 'Ethereum', zh: '以太坊' },
};

export const dcaLabels = {
  title: { en: 'DCA Simulation', zh: '定投模拟' }, startMonth: { en: 'Start Month', zh: '开始月份' }, weeklyInvestment: { en: 'Weekly Investment per Asset', zh: '每个标的每周定投金额' }, selectedAssets: { en: 'Selected Assets', zh: '已选标的' }, benchmarks: { en: 'Benchmarks', zh: '市场基准' }, comparisonTable: { en: 'Comparison Table', zh: '对比结果' }, performanceComparison: { en: 'DCA Performance Comparison', zh: '定投表现对比' }, totalInvested: { en: 'Total Invested', zh: '总投入' }, currentValue: { en: 'Current Value', zh: '当前总市值' }, totalProfit: { en: 'Total Profit', zh: '累计盈利' }, totalReturn: { en: 'Total Return', zh: '累计收益率' }, maximumDrawdown: { en: 'Maximum Drawdown', zh: '最大回撤' }, totalPurchases: { en: 'Total Purchases', zh: '定投次数' }, totalShares: { en: 'Total Shares / Units', zh: '累计份额' }, averageCost: { en: 'Average Cost', zh: '平均成本' }, source: { en: 'Data Source', zh: '数据源' }, normalized: { en: 'Normalized', zh: '标准化' }, portfolioValue: { en: 'Portfolio Value', zh: '组合价值' },
} satisfies Record<string, BilingualLabel>;

export const researchLabels = {
  title: { en: 'Research', zh: '研究' }, spmoTopHolding: { en: 'SPMO Top Holding Strategy', zh: 'SPMO 第一大持仓策略回测' }, cagr: { en: 'CAGR', zh: '年化收益率' }, maximumDrawdown: { en: 'Maximum Drawdown', zh: '最大回撤' }, annualizedVolatility: { en: 'Annualized Volatility', zh: '年化波动率' }, sharpeRatio: { en: 'Sharpe Ratio', zh: '夏普比率' }, numberOfTrades: { en: 'Number of Trades', zh: '换仓次数' },
} satisfies Record<string, BilingualLabel>;

export const macroLabels: Record<string, BilingualLabel> = {
  cpi: { en: 'CPI (YoY)', zh: '消费者物价指数（同比）' }, coreCpi: { en: 'Core CPI (YoY)', zh: '核心CPI（同比）' }, pce: { en: 'PCE Price Index', zh: '个人消费支出价格指数' }, corePce: { en: 'Core PCE Price Index', zh: '核心PCE价格指数' }, nonfarmPayrolls: { en: 'Nonfarm Payrolls', zh: '非农就业' }, unemploymentRate: { en: 'Unemployment Rate', zh: '失业率' }, gdp: { en: 'GDP (QoQ)', zh: 'GDP（环比）' }, effectiveFedFundsRate: { en: 'Fed Funds Rate', zh: '联邦基金利率' },
};

const calendarEventLabels: Record<string, BilingualLabel> = {
  'Core CPI (MoM)': { en: 'Core CPI (MoM)', zh: '核心CPI（月率）' }, 'Eurozone CPI (YoY)': { en: 'Eurozone CPI (YoY)', zh: '欧元区消费者物价指数（同比）' }, 'PBOC Loan Prime Rate (1Y)': { en: 'PBOC Loan Prime Rate (1Y)', zh: '中国贷款市场报价利率（1年期）' }, 'Fed Chair Speech': { en: 'Fed Chair Speech', zh: '美联储主席讲话' }, 'CPI (YoY)': { en: 'CPI (YoY)', zh: '消费者物价指数（同比）' }, 'Retail Sales (MoM)': { en: 'Retail Sales (MoM)', zh: '零售销售（月率）' }, 'ECB Interest Rate Decision': { en: 'ECB Interest Rate Decision', zh: '欧洲央行利率决议' }, 'ECB President Press Conference': { en: 'ECB President Press Conference', zh: '欧洲央行行长新闻发布会' }, 'Japan CPI (YoY)': { en: 'Japan CPI (YoY)', zh: '日本消费者物价指数（同比）' }, 'UK CPI (YoY)': { en: 'UK CPI (YoY)', zh: '英国消费者物价指数（同比）' }, 'UK GDP (MoM)': { en: 'UK GDP (MoM)', zh: '英国GDP（月率）' }, 'BOJ Interest Rate Decision': { en: 'BOJ Interest Rate Decision', zh: '日本央行利率决议' }, 'BOJ Governor Press Conference': { en: 'BOJ Governor Press Conference', zh: '日本央行行长新闻发布会' }, 'PPI (MoM)': { en: 'PPI (MoM)', zh: '生产者物价指数（月率）' }, 'FOMC Interest Rate Decision': { en: 'FOMC Interest Rate Decision', zh: '美联储利率决议' }, 'FOMC Press Conference': { en: 'FOMC Press Conference', zh: '美联储新闻发布会' }, 'PCE Price Index (MoM)': { en: 'PCE Price Index (MoM)', zh: '个人消费支出价格指数（月率）' }, 'Core PCE Price Index (MoM)': { en: 'Core PCE Price Index (MoM)', zh: '核心PCE价格指数（月率）' }, 'China CPI (YoY)': { en: 'China CPI (YoY)', zh: '中国消费者物价指数（同比）' }, 'China PPI (YoY)': { en: 'China PPI (YoY)', zh: '中国生产者物价指数（同比）' }, 'Nonfarm Payrolls': { en: 'Nonfarm Payrolls', zh: '非农就业' }, 'Unemployment Rate': { en: 'Unemployment Rate', zh: '失业率' }, 'GDP (Annualized QoQ)': { en: 'GDP (Annualized QoQ)', zh: 'GDP（年化季率）' }, 'ISM Manufacturing PMI': { en: 'ISM Manufacturing PMI', zh: 'ISM制造业PMI' }, 'ISM Services PMI': { en: 'ISM Services PMI', zh: 'ISM服务业PMI' }, 'Eurozone GDP (QoQ)': { en: 'Eurozone GDP (QoQ)', zh: '欧元区GDP（季率）' }, 'Eurozone Composite PMI': { en: 'Eurozone Composite PMI', zh: '欧元区综合PMI' }, 'China GDP (YoY)': { en: 'China GDP (YoY)', zh: '中国GDP（同比）' }, 'China Manufacturing PMI': { en: 'China Manufacturing PMI', zh: '中国制造业PMI' }, 'BOE Interest Rate Decision': { en: 'BOE Interest Rate Decision', zh: '英国央行利率决议' }, 'Initial Jobless Claims': { en: 'Initial Jobless Claims', zh: '首次申请失业救济人数' },
};

export function getCalendarEventLabel(event: string): BilingualLabel { return calendarEventLabels[event] ?? { en: event, zh: '经济事件' }; }

const keyPeopleRoleLabels: Record<string, BilingualLabel> = {
  'Jerome Powell': { en: 'Chair, Federal Reserve', zh: '美联储主席' }, 'Jensen Huang': { en: 'NVIDIA CEO', zh: '英伟达CEO' }, 'Elon Musk': { en: 'Tesla CEO', zh: '特斯拉CEO' }, 'Sam Altman': { en: 'OpenAI CEO', zh: 'OpenAI首席执行官' }, CZ: { en: 'Crypto Executive', zh: '加密行业高管' }, 'Donald Trump': { en: 'Policy Figure', zh: '政策人物' }, 'Christine Lagarde': { en: 'President, ECB', zh: '欧洲央行行长' }, 'Kazuo Ueda': { en: 'Governor, Bank of Japan', zh: '日本央行行长' },
};

export function getKeyPersonRoleLabel(person: string, fallbackRole: string): BilingualLabel { return keyPeopleRoleLabels[person] ?? { en: fallbackRole, zh: '市场相关人物' }; }

export const tableLabels = {
  maturity: { en: 'Maturity', zh: '期限' }, yield: { en: 'Yield', zh: '收益率' }, oneDayChange: { en: '1D Change', zh: '单日变化' }, symbol: { en: 'Symbol', zh: '代码' }, price: { en: 'Price', zh: '价格' }, indicator: { en: 'Indicator', zh: '指标' }, latest: { en: 'Latest', zh: '最新值' }, source: { en: 'Data Source', zh: '数据源' }, status: { en: 'Status', zh: '状态' }, time: { en: 'Time', zh: '时间' }, event: { en: 'Event', zh: '事件' }, country: { en: 'Country', zh: '国家/地区' }, impact: { en: 'Impact', zh: '重要程度' },
} satisfies Record<string, BilingualLabel>;

export const statusLabels: Record<'real' | 'cache' | 'fallback' | 'mock', BilingualLabel> = { real: { en: 'Real', zh: '实时' }, cache: { en: 'Cached', zh: '缓存' }, fallback: { en: 'Fallback', zh: '备用数据' }, mock: { en: 'Mock', zh: '模拟数据' } };
export const sessionLabels: Record<'overnight' | 'pre' | 'regular' | 'after' | 'closed', BilingualLabel> = { overnight: { en: 'OVERNIGHT', zh: '夜盘' }, pre: { en: 'PRE', zh: '盘前' }, regular: { en: 'REGULAR', zh: '正常交易' }, after: { en: 'AFTER', zh: '盘后' }, closed: { en: 'CLOSED', zh: '休市' } };
